# nginx: include this snippet inside your http{} or server{} block
# Example:  include /etc/nginx/snippets/clickonce-mime.conf;
types {
    application/x-ms-application  application;
    application/x-ms-manifest     manifest;
    application/octet-stream      deploy;
}
